-- TB_ADVERTISEMENT (광고 테이블)
CREATE TABLE TB_ADVERTISEMENT
(
    AD_ID          VARCHAR(50)    NOT NULL PRIMARY KEY COMMENT '광고 ID',
    AD_NAME        VARCHAR(100)   NOT NULL COMMENT '광고 이름',
    AD_TYPE        VARCHAR(10)    NOT NULL COMMENT '광고 유형',
    AD_LOCATION    VARCHAR(50)    NOT NULL COMMENT '노출위치',
    MEDIA_URL      VARCHAR(255)   NOT NULL COMMENT '미디어 URL/ID',
    LINK_URL       VARCHAR(255) COMMENT '연결 URL',
    VIDEO_DURATION DECIMAL(10, 0) NOT NULL DEFAULT 0 COMMENT '영상 길이',
    START_DATE     DATE           NOT NULL COMMENT '시작 일자',
    END_DATE       DATE COMMENT '종료 일자',
    SORT_ORDER     DECIMAL(10, 0) NOT NULL DEFAULT 0 COMMENT '정렬 순서',
    IS_ACTIVE      CHAR(1)        NOT NULL DEFAULT 'Y' COMMENT '활성화 여부',
    CREATED_DATE   DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일자',
    CREATED_BY     VARCHAR(50) COMMENT '생성자',
    UPDATED_DATE   DATETIME COMMENT '수정 일자',
    UPDATED_BY     VARCHAR(50) COMMENT '수정자'
) COMMENT='광고 관련';