-- TB_AI_USAGE_LOG (AI 토큰 사용량 로그 테이블)
CREATE TABLE TB_AI_USAGE_LOG
(
    USAGE_LOG_ID  DECIMAL(10, 0) NOT NULL PRIMARY KEY COMMENT '로그 ID',
    USER_ID       VARCHAR(50)    NOT NULL COMMENT '사용자 ID',
    FEATURE_TYPE  VARCHAR(20)    NOT NULL COMMENT '기능 유형',
    INPUT_TOKENS  DECIMAL(10, 0) NOT NULL DEFAULT 0 COMMENT '입력 토큰 수',
    OUTPUT_TOKENS DECIMAL(10, 0) NOT NULL DEFAULT 0 COMMENT '출력 토큰 수',
    TOTAL_COST    DECIMAL(10, 0) NOT NULL DEFAULT 0 COMMENT '예상 비용',
    LOG_DATE      DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '기록 일시',
    CREATED_DATE  DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일자',
    CREATED_BY    VARCHAR(50) COMMENT '생성자',
    UPDATED_DATE  DATETIME COMMENT '수정 일자',
    UPDATED_BY    VARCHAR(50) COMMENT '수정자',
    FOREIGN KEY (USER_ID) REFERENCES TB_USER (USER_ID)
) COMMENT='AI 토큰 사용량 로그 정보';