-- TB_BATTLE_LOG (배틀 로그 테이블)
CREATE TABLE TB_BATTLE_LOG
(
    BATTLE_ID    VARCHAR(50)    NOT NULL PRIMARY KEY COMMENT '배틀 ID',
    CHARACTER_ID VARCHAR(50)    NOT NULL COMMENT '캐릭터 ID',
    BATTLE_TYPE  VARCHAR(10)    NOT NULL COMMENT '전투 유형: PVE',
    OPPONENT_ID  VARCHAR(50)    NOT NULL COMMENT '상대방 ID (PVP: 상대방 ID, PVE: 몬스터 ID)',
    IS_WIN       CHAR(1)        NOT NULL DEFAULT 'N' COMMENT '승리 여부: Y: 승리, N: 패배',
    TURN_COUNT   DECIMAL(20, 0) NOT NULL DEFAULT 0 COMMENT '최종 턴 수',
    CREATED_DATE DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일자',
    CREATED_BY   VARCHAR(50) COMMENT '생성자',
    UPDATED_DATE DATETIME COMMENT '수정 일자',
    UPDATED_BY   VARCHAR(50) COMMENT '수정자',
    FOREIGN KEY (CHARACTER_ID) REFERENCES TB_CHARACTER (CHARACTER_ID),
    FOREIGN KEY (OPPONENT_ID) REFERENCES TB_USER (USER_ID) 또는 TB_MONSTER(MONSTER_ID)
) COMMENT='배틀 로그 정보';
) COMMENT='배틀 로그 정보';