-- TB_BATTLE_ACTION (턴별 전투 로그 테이블)
CREATE TABLE TB_BATTLE_ACTION
(
    ACTION_ID    DECIMAL(10, 0) NOT NULL PRIMARY KEY COMMENT '액션 ID',
    BATTLE_ID    VARCHAR(50)    NOT NULL COMMENT '전투 ID',
    COMMAND_ID   VARCHAR(50) COMMENT '커맨드 ID',
    TURN_NUMBER  DECIMAL(10, 0) NOT NULL COMMENT '턴 번호',
    ACTOR_TYPE   VARCHAR(10)    NOT NULL COMMENT '행위자 유형: CHARACTER, MONSTER, OPPONENT',
    DAMAGE_DEALT DECIMAL(10, 0) NOT NULL DEFAULT 0 COMMENT '가한 피해량',
    GPT_MESSAGE  VARCHAR(4000) COMMENT 'GPT 메시지',
    ACTION_DATE  DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '발생 일시',
    CREATED_DATE DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일자',
    CREATED_BY   VARCHAR(50) COMMENT '생성자',
    UPDATED_DATE DATETIME COMMENT '수정 일자',
    UPDATED_BY   VARCHAR(50) COMMENT '수정자',
    FOREIGN KEY (BATTLE_ID) REFERENCES TB_BATTLE_LOG (BATTLE_ID),
    FOREIGN KEY (COMMAND_ID) REFERENCES TB_COMMAND (COMMAND_ID)
) COMMENT='턴별 전투 로그 정보';