-- TB_CHARACTER_PERSONALITY (캐릭터 성격 테이블)
CREATE TABLE TB_CHARACTER_PERSONALITY
(
    CHARACTER_PERSONALITY_ID INT NOT NULL PRIMARY KEY COMMENT '성격 ID',
    PERSONALITY_DESCRIPTION  VARCHAR(255) COMMENT '설명'
) COMMENT='캐릭터 성격 정보';