-- TB_CHARACTER (캐릭터 테이블)
CREATE TABLE TB_CHARACTER
(
    CHARACTER_ID             INT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '캐릭터 ID',
    CHARACTER_NAME           VARCHAR(50) NOT NULL UNIQUE KEY COMMENT '캐릭터 이름',
    USER_ID                  VARCHAR(50) NOT NULL COMMENT '사용자 ID'
    IMAGE_ID                 VARCHAR(50) NOT NULL COMMENT '캐릭터 이미지 ID',
    CHARACTER_PERSONALITY_ID VARCHAR(50) NOT NULL COMMENT '캐릭터 성격 ID',
    GRADE_ID                 INT NOT NULL COMMENT '캐릭터 등급',
    TOTAL_STAGE_CLEARS       INT NOT NULL COMMENT '총 클리어 횟수',
    EVOLUTION_STEP           INT NOT NULL COMMENT '현재 진화 단계',
    CREATED_DATE             DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일자',
    CREATED_BY               VARCHAR(50) COMMENT '생성자',
    UPDATED_DATE             DATETIME COMMENT '수정 일자',
    UPDATED_BY               VARCHAR(50) COMMENT '수정자'
) COMMENT='캐릭터 정보';