-- TB_CHARACTER (캐릭터 테이블)
CREATE TABLE TB_CHARACTER_STAT
(
    CHARACTER_ID      VARCHAR(50) NOT NULL PRIMARY KEY COMMENT '캐릭터 ID',
    CHARACTER_HP      INT(100) NOT NULL COMMENT '캐릭터 체력',
    CHARACTER_ATTACK  INT(100) NOT NULL COMMENT '캐릭터 공격력',
    CHARACTER_DEFENSE INT(100) NOT NULL COMMENT '캐릭터 방어력',
    CHARACTER_SPEED   INT(5) NOT NULL COMMENT '캐릭터 속도',
    CRITICAL_RATE     INT(100) NOT NULL COMMENT '크리티컬 확률',
    CREATED_DATE      DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일자',
    CREATED_BY        VARCHAR(50) COMMENT '생성자',
    UPDATED_DATE      DATETIME COMMENT '수정 일자',
    UPDATED_BY        VARCHAR(50) COMMENT '수정자'
) COMMENT='캐릭터 정보';