-- TB_COMMUNITY_REPORT (커뮤니티 신고 기록 테이블)
CREATE TABLE TB_COMMUNITY_REPORT
(
    REPORT_ID          DECIMAL(10, 0) NOT NULL PRIMARY KEY COMMENT '신고 ID',
    USER_ID            VARCHAR(50)    NOT NULL COMMENT '신고자 ID',
    TARGET_TYPE        VARCHAR(20)    NOT NULL COMMENT '신고 대상 유형',
    TARGET_ID          VARCHAR(50)    NOT NULL COMMENT '시고 대상 ID',
    REPORT_REASON_CODE VARCHAR(20) COMMENT '신고 사유 코드',
    DETAIL_REASON      VARCHAR(4000) COMMENT '상세 사유',
    REPORT_STATUS      VARCHAR(20)    NOT NULL COMMENT '처리 상태',
    REPORT_DATE        DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '신고 일시',
    PROCESS_DATE       DATETIME COMMENT '처리 일시',
    CREATED_DATE       DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일자',
    CREATED_BY         VARCHAR(50) COMMENT '생성자',
    UPDATED_DATE       DATETIME COMMENT '수정 일자',
    UPDATED_BY         VARCHAR(50) COMMENT '수정자',
    FOREIGN KEY (USER_ID) REFERENCES TB_USER (USER_ID)
) COMMENT='커뮤니티 신고 기록 정보';