-- TB_COMMUNITY_LIKE (커뮤니티 좋아요 기록 테이블)
CREATE TABLE TB_COMMUNITY_LIKE
(
    USER_ID      VARCHAR(50)    NOT NULL COMMENT '사용자 ID',
    POST_ID      DECIMAL(10, 0) NOT NULL COMMENT '게시글 ID',
    LOG_DATE     DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '기록 일시',
    CREATED_DATE DATETIME                DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일자',
    CREATED_BY   VARCHAR(50) COMMENT '생성자',
    UPDATED_DATE DATETIME COMMENT '수정 일자',
    UPDATED_BY   VARCHAR(50) COMMENT '수정자',
    PRIMARY KEY (USER_ID, POST_ID),
    FOREIGN KEY (USER_ID) REFERENCES TB_USER (USER_ID),
    FOREIGN KEY (POST_ID) REFERENCES TB_COMMUNITY_POST (POST_ID)
) COMMENT='커뮤니티 좋아요 기록 정보';