-- TB_COMMAND (커맨드 테이블)
CREATE TABLE TB_COMMAND
(
    COMMAND_ID          VARCHAR(50) NOT NULL PRIMARY KEY COMMENT '커맨드 ID',
    COMMAND_TYPE        VARCHAR(20) NOT NULL COMMENT '커맨드 유형',
    COMMAND_DESCRIPTION VARCHAR(255) COMMENT '커맨드 설명',
    CREATED_DATE        DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일자',
    CREATED_BY          VARCHAR(50) COMMENT '생성자',
    UPDATED_DATE        DATETIME COMMENT '수정 일자',
    UPDATED_BY          VARCHAR(50) COMMENT '수정자'
) COMMENT='커맨드 정보';