-- TB_COMMUNITY_POST (커뮤니티 게시글 테이블)
CREATE TABLE TB_COMMUNITY_POST
(
    POST_ID       DECIMAL(10, 0) NOT NULL PRIMARY KEY COMMENT '게시글 ID',
    USER_ID       VARCHAR(50)    NOT NULL COMMENT '작성자 ID',
    CATEGORY_CODE VARCHAR(20)    NOT NULL COMMENT '게시판 구분 코드',
    TITLE         VARCHAR(255)   NOT NULL COMMENT '제목',
    CONTENT       VARCHAR(4000)  NOT NULL COMMENT '내용',
    VIEW_COUNT    DECIMAL(10, 0) NOT NULL DEFAULT 0 COMMENT '조회수',
    LIKE_COUNT    DECIMAL(10, 0) NOT NULL DEFAULT 0 COMMENT '좋아요 수',
    IS_DELETED    CHAR(1)        NOT NULL DEFAULT 'N' COMMENT '삭제 여부',
    CREATED_DATE  DATETIME                DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일자',
    CREATED_BY    VARCHAR(50) COMMENT '생성자',
    UPDATED_DATE  DATETIME COMMENT '수정 일자',
    UPDATED_BY    VARCHAR(50) COMMENT '수정자',
    FOREIGN KEY (USER_ID) REFERENCES TB_USER (USER_ID),
    FOREIGN KEY (CATEGORY_CODE) REFERENCES TB_CODE (CATEGORY_CODE)
) COMMENT='커뮤니티 게시글 정보';