-- TB_DIALOGUE (AI/ 캐릭터 대화 기록 테이블)
CREATE TABLE TB_DIALOGUE
(
    DIALOGUE_ID     DECIMAL(10, 0) NOT NULL PRIMARY KEY COMMENT '대화 ID',
    USER_ID         VARCHAR(50)    NOT NULL COMMENT '사용자 ID',
    CHARACTER_ID    VARCHAR(50)    NOT NULL COMMENT '캐릭터 ID',
    SPEAKER_TYPE    VARCHAR(10)    NOT NULL COMMENT '화자 유형: AI(CHARACTER), USER',
    MESSAGE_CONTENT VARCHAR(4000)  NOT NULL COMMENT '메시지 내용',
    CONTEXT_TAG     VARCHAR(50) COMMENT '대화 맥락 태그',
    LOG_DATE        DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '기록 일시',
    CREATED_DATE    DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일자',
    CREATED_BY      VARCHAR(50) COMMENT '생성자',
    UPDATED_DATE    DATETIME COMMENT '수정 일자',
    UPDATED_BY      VARCHAR(50) COMMENT '수정자',
    FOREIGN KEY (USER_ID) REFERENCES TB_USER (USER_ID),
    FOREIGN KEY (CHARACTER_ID) REFERENCES TB_CHARACTER (CHARACTER_ID)
) COMMENT='AI/ 캐릭터 대화 기록 정보';