-- TB_GROWTH_RULE (성장 규칙 테이블)
CREATE TABLE TB_GROWTH_RULE
(
    RULE_ID               VARCHAR(50)    NOT NULL PRIMARY KEY COMMENT '성장 규칙 ID',
    MINIGAME_ID           VARCHAR(50) COMMENT '미니게임 ID',
    IMAGE_ID              VARCHAR(50) COMMENT '진화 이미지 ID',
    REQUIRED_CLEARS       DECIMAL(10, 0) NOT NULL DEFAULT 0 COMMENT '필요 클리어 횟수',
    TARGET_EVOLUTION_STEP DECIMAL(10, 0) COMMENT '목표 진화 단계',
    CREATED_DATE          DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일자',
    CREATED_BY            VARCHAR(50) COMMENT '생성자',
    UPDATED_DATE          DATETIME COMMENT '수정 일자',
    UPDATED_BY            VARCHAR(50) COMMENT '수정자',
    FOREIGN KEY (IMAGE_ID) REFERENCES TB_IMAGE (IMAGE_ID),
    FOREIGN KEY (MINIGAME_ID) REFERENCES TB_MINI_GAME (MINI_GAME_ID)
) COMMENT='성장 규칙 정보';