-- TB_IMAGE (이미지 테이블)
CREATE TABLE TB_IMAGE
(
    IMAGE_ID     INT(50) NOT NULL PRIMARY KEY COMMENT '이미지 ID',
    IMAGE_NAME   VARCHAR2(100) NOT NULL COMMENT '이미지 주소',
    IMAGE_TYPE   INT(100) NOT NULL COMMENT '이미지 타입',
    CREATED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일자',
    CREATED_BY   VARCHAR(50) COMMENT '생성자',
    UPDATED_DATE DATETIME COMMENT '수정 일자',
    UPDATED_BY   VARCHAR(50) COMMENT '수정자'
) COMMENT='이미지 정보';