-- TB_MINI_GAME (미니 게임 테이블)
CREATE TABLE TB_MINI_GAME
(
    MINI_GAME_ID          VARCHAR(50)  NOT NULL PRIMARY KEY COMMENT '미니 게임 ID',
    MINI_GAME_NAME        VARCHAR(100) NOT NULL COMMENT '미니 게임 이름',
    MINI_GAME_DESCRIPTION VARCHAR(255) COMMENT '미니 게임 설명',
    CREATED_DATE          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일자',
    CREATED_BY            VARCHAR(50) COMMENT '생성자',
    UPDATED_DATE          DATETIME COMMENT '수정 일자',
    UPDATED_BY            VARCHAR(50) COMMENT '수정자'
) COMMENT='미니 게임 정보';