-- TB_MONSTER (몬스터 테이블)
CREATE TABLE TB_MONSTER
(
    MONSTER_ID            VARCHAR(50)  NOT NULL PRIMARY KEY COMMENT '몬스터 ID',
    IMAGE_ID              VARCHAR(50)  NOT NULL COMMENT '이미지 ID',
    MONSTER_NAME          VARCHAR(100) NOT NULL COMMENT '몬스터 이름',
    MONSTER_TYPE          VARCHAR(20)  NOT NULL DEFAULT 'NORMAL' COMMENT '몬스터 유형: NOMAL, BOSS',
    MONSTER_HP            INT          NOT NULL COMMENT '몬스터 체력',
    MONSTER_ATTACK        INT          NOT NULL COMMENT '몬스터 공격력',
    MONSTER_DEFENSE       INT          NOT NULL COMMENT '몬스터 방어력',
    MONSTER_CRITICAL_RATE INT COMMENT '몬스터 크리티컬 확률',
    CREATED_DATE          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일자',
    CREATED_BY            VARCHAR(50) COMMENT '생성자',
    UPDATED_DATE          DATETIME COMMENT '수정 일자',
    UPDATED_BY            VARCHAR(50) COMMENT '수정자',
    FOREIGN KEY (IMAGE_ID) REFERENCES TB_IMAGE (IMAGE_ID)
) COMMENT='몬스터 정보';