CREATE TABLE TB_NOTICE
(
    NOTICE_ID           INT          NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '공지사항 고유 번호 (PK)',
    NOTICE_TITLE        VARCHAR(255) NOT NULL COMMENT '공지사항 제목',
    NOTICE_CONTENT      TEXT         NOT NULL COMMENT '공지사항 내용',
    NOTICE_VIEW_COUNT   INT          NOT NULL DEFAULT 0 COMMENT '조회수',
    IS_PINNED           TINYINT(1)   NOT NULL DEFAULT 0 COMMENT '상단 고정 여부 (0:미고정, 1:고정)',
    CREATED_BY          VARCHAR(50)  NOT NULL COMMENT '생성자 ID (TB_USER의 USER_ID 참조)',
    CREATED_DATE        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일자',
    LAST_MODIFIED_BY    VARCHAR(50) COMMENT '최종 수정자 ID (TB_USER의 USER_ID 참조)',
    LAST_MODIFIED_DATE  DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '최종 수정 일자'
) COMMENT='공지사항 정보';