-- TB_PRODUCT (상품 테이블)
CREATE TABLE TB_PRODUCT
(
    PRODUCT_ID    VARCHAR(10)    NOT NULL PRIMARY KEY COMMENT '상품 ID',
    PRODUCT_NAME  VARCHAR(100)   NOT NULL COMMENT '상품명',
    PRODUCT_TYPE  VARCHAR(20)    NOT NULL COMMENT '상품 유형: 뽑기권, 광고제거',
    PRICE         DECIMAL(10, 0) NOT NULL DEFAULT 0 COMMENT '가격',
    CURRENCY_TYPE VARCHAR(10)    NOT NULL DEFAULT 'KRW' COMMENT '통화 유형',
    IS_SALE       CHAR(1)        NOT NULL DEFAULT 'Y' COMMENT '판매 여부',
    CREATED_DATE  DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일자',
    CREATED_BY    VARCHAR(50) COMMENT '생성자',
    UPDATED_DATE  DATETIME COMMENT '수정 일자',
    UPDATED_BY    VARCHAR(50) COMMENT '수정자'
) COMMENT='상품 정보';