-- TB_PERSONA (페르소나 테이블)
CREATE TABLE TB_PERSONA
(
    PERSONA_ID               VARCHAR(50)   NOT NULL PRIMARY KEY COMMENT '페르소나 ID',
    CHARACTER_ID             VARCHAR(50) COMMENT '캐릭터 ID',
    USER_ID                  VARCHAR(100)  NOT NULL COMMENT '유저 아이디',
    INSTRUCTION_PROMPT       VARCHAR(4000) NOT NULL COMMENT 'GPT 지시 프롬프트',
    BACKGROUND_INFO          VARCHAR(4000) COMMENT '배경 정보',
    CHARACTER_PERSONALITY_ID INT           NOT NULL COMMENT '성격',
    CREATED_DATE             DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일자',
    CREATED_BY               VARCHAR(50) COMMENT '생성자',
    UPDATED_DATE             DATETIME COMMENT '수정 일자',
    UPDATED_BY               VARCHAR(50) COMMENT '수정자',
    FOREIGN KEY (USER_ID) REFERENCES TB_USER (USER_ID),
    FOREIGN KEY (CHARACTER_PERSONALITY_ID) REFERENCES TB_CHARACTER_PERSONALITY (CHARACTER_PERSONALITY_ID),
    FOREIGN KEY (CHARACTER_ID) REFERENCES TB_CHARACTER (CHARACTER_ID)
) COMMENT='페르소나 정보';