-- TB_PAYMENT (결제 기록 테이블)
CREATE TABLE TB_PAYMENT
(
    PAYMENT_ID     VARCHAR(100)   NOT NULL PRIMARY KEY COMMENT '결제 ID',
    USER_ID        VARCHAR(50)    NOT NULL COMMENT '사용자 ID',
    PRODUCT_ID     VARCHAR(50)    NOT NULL COMMENT '상품 ID',
    AMOUNT         DECIMAL(10, 0) NOT NULL DEFAULT 0 COMMENT '결제 금액',
    PAYMENT_STATUS VARCHAR(20)    NOT NULL DEFAULT 'PENDING' COMMENT '결제 상태',
    PAYMENT_METHOD VARCHAR(50) COMMENT '결제 수단',
    PAYMENT_DATE   DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '결제 일시',
    CREATED_DATE   DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일자',
    CREATED_BY     VARCHAR(50) COMMENT '생성자',
    UPDATED_DATE   DATETIME COMMENT '수정 일자',
    UPDATED_BY     VARCHAR(50) COMMENT '수정자',
    FOREIGN KEY (USER_ID) REFERENCES TB_USER (USER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES TB_PRODUCT (PRODUCT_ID)
) COMMENT='결제 기록 정보';