-- TB_RANKING (랭킹 테이블)
CREATE TABLE TB_RANKING
(
    RANKING_ID   DECIMAL(10, 0) NOT NULL PRIMARY KEY COMMENT '랭킹 ID',
    USER_ID      VARCHAR(50)    NOT NULL COMMENT '사용자 ID',
    RANKING_TYPE VARCHAR(20)    NOT NULL COMMENT '랭킹 유형',
    SCORE        DECIMAL(10, 0) NOT NULL DEFAULT 0 COMMENT '점수 / 기준 값',
    RANK_VALUE   DECIMAL(10, 0) NOT NULL COMMENT '현재 순위',
    REFRESH_DATE DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '갱신 일자',
    CREATED_DATE DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일자',
    CREATED_BY   VARCHAR(50) COMMENT '생성자',
    UPDATED_DATE DATETIME COMMENT '수정 일자',
    UPDATED_BY   VARCHAR(50) COMMENT '수정자',
    FOREIGN KEY (USER_ID) REFERENCES TB_USER (USER_ID)
) COMMENT='랭킹 정보';