-- TB_USER_PRODUCT (유저 상품/재화 테이블)
CREATE TABLE TB_USER_PRODUCT
(
    USER_PRODUCT_ID DECIMAL(10, 0) NOT NULL PRIMARY KEY COMMENT '유저 상품 ID',
    USER_ID         VARCHAR(50)    NOT NULL COMMENT '사용자 ID',
    PRODUCT_ID      VARCHAR(50)    NOT NULL COMMENT '상품 ID',
    QUANTITY        DECIMAL(10, 0) NOT NULL DEFAULT 0 COMMENT '보유 수량',
    CREATED_DATE    DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일자',
    CREATED_BY      VARCHAR(50) COMMENT '생성자',
    UPDATED_DATE    DATETIME COMMENT '수정 일자',
    UPDATED_BY      VARCHAR(50) COMMENT '수정자',
    FOREIGN KEY (USER_ID) REFERENCES TB_USER (USER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES TB_PRODUCT (PRODUCT_ID)
) COMMENT='유저 상품/재화 정보';