-- TB_USER_EMAIL_VERIFY (이메일 인증 테이블)
CREATE TABLE TB_USER_EMAIL_VERIFY
(
    USER_ID      VARCHAR(50)  NOT NULL PRIMARY KEY COMMENT '사용자 ID',
    VERIFY_ID    VARCHAR(50)  NOT NULL AUTO_INCREMENT COMMENT '인증 ID',
    EMAIL        VARCHAR(100) NOT NULL COMMENT '이메일 주소',
    VERIFY_CODE  VARCHAR(100) NOT NULL COMMENT '인증 코드',
    EXPIRY_DATE  DATETIME     NOT NULL COMMENT '만료 일시',
    IS_VERIFIED  CHAR(1)      NOT NULL DEFAULT 'N' COMMENT '인증 성공 여부',
    CREATED_DATE DATETIME COMMENT '생성 일자',
    CREATED_BY   VARCHAR(50) COMMENT '생성자',
    UPDATED_DATE DATETIME COMMENT '수정일자',
    UPDATED_BY   VARCHAR(50) COMMENT '수정자'
) COMMENT='이메일 인증 정보';