-- TB_USER (사용자 테이블)
CREATE TABLE TB_USER
(
    USER_ID       VARCHAR(50)  NOT NULL PRIMARY KEY COMMENT '사용자 ID',
    USER_NAME     VARCHAR(100) NOT NULL COMMENT '사용자 이름',
    USER_EMAIL    VARCHAR(100) NOT NULL UNIQUE KEY COMMENT '인증 및 알림용 이메일',
    IS_EMAIL_VERIFIED CHAR(1) NOT NULL DEFAULT 'N' COMMENT '이메일 인증 완료 여부 (Y/N)',
    USER_PASSWORD VARCHAR(255) NOT NULL COMMENT '사용자 비밀번호',
    USER_NICKNAME VARCHAR(50)  NOT NULL UNIQUE KEY COMMENT '유저 닉네임',
    IMAGE_ID      INT COMMENT '프로필 이미지',
    CREATED_DATE  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일자',
    ROLE          VARCHAR(20) COMMENT '유저타입 구분'
) COMMENT='사용자 정보';